package structs

// Group is the struct that sets the `group` entity on the domain
//   for domains type `backd`:
//     - group
//   for domains type `active directory`:
//     - group can be a reference to an Active Directory group
//         if group is created with the same name that already exists
//         on the remote domain
type Group struct {
	ID          string `json:"_id" bson:"_id"`             // (required - autogenerated)
	Name        string `json:"name,omitempty" bson:"name"` // (required) Name of the group
	Description string `json:"desc,omitempty" bson:"desc"` // (optional) Description
	Metadata    `json:"meta" bson:"meta"`
}

// GroupValidator is the JSON schema validation for the groups collection
func GroupValidator() map[string]interface{} {

	return BuildValidator(
		map[string]interface{}{
			"_id": map[string]interface{}{
				"bsonType": "string",
				"pattern":  "^[a-zA-Z0-9]{20}$",
			},
			"name": map[string]interface{}{
				"bsonType": "string",
			},
			"desc": map[string]interface{}{
				"bsonType": "string",
			},
		},
		[]string{"_id", "name"},
	)

}

// Indexes
var (
	GroupIndexes = []Index{
		{
			Fields: []string{"_id"},
			Unique: true,
		},
		{
			Fields: []string{"name"},
			Unique: true,
		},
	}
)
