apiVersion: apps/v1
kind: Deployment
metadata:
  name: sessions
  labels:
    app: sessions
  namespace: backd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sessions
  template:
    metadata:
      labels:
        app: sessions
    spec:
      containers:
      - name: sessions
        image: backd/sessions:arm
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        - containerPort: 8182
        env:
        - name: MONGO_URL
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: mongo-url
